"""Pydantic schemas for the AI query feature."""
from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """Request body for POST /ask — submit a natural-language question."""

    question: str = Field(
        description="Natural-language question about trades, spikes, P&L, or system health.",
        example="Which strike performed best today?",
    )
    context: dict | None = Field(
        default=None,
        description="Optional extra context passed to the LLM (rarely needed).",
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {"question": "What was the last trade?"},
                {"question": "Show today's losing trades."},
                {"question": "Which strike performed best?"},
                {"question": "Compare CE vs PE profitability."},
            ]
        }
    }


class AskResponse(BaseModel):
    """Response from the AI query layer."""

    answer: str = Field(
        description="Natural-language answer generated by the LLM, grounded in live trade data.",
        example="The best performing strike was NIFTY 22450 CE with total P&L of 847.20 across 9 trades.",
    )
    model: str = Field(
        description="LLM model ID that generated the answer.",
        example="llama-3.3-70b-versatile",
    )
    turns: int = Field(
        description=(
            "Number of LLM turns used (typically 2: one tool-call turn to fetch data, "
            "one answer turn). Higher values indicate the model needed extra reasoning steps."
        ),
        example=2,
    )
